# Jupyter Book configuration
# See https://jupyterbook.org/customize/config.html

title: Parallel Critiques â€” Analyzing Rhetorical Extremism
author: Savantlab
language: en
only_build_toc_files: true

html:
  favicon: null
  use_issues_button: false
  use_edit_page_button: false
  use_repository_button: false
  baseurl: ""
  extra_footer: |
    <p>Built with Jupyter Book.</p>

launch_buttons:
  binderhub_url: https://mybinder.org
  thebe: true
  notebook_interface: classic

parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
